dvmn_flowers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('', views.main_page, name='main_page'),
    path('catalog/', views.catalog, name='catalog'),
    path('catalog/<int:id>/', views.show_card, name='card'),
    path('order/', views.order, name='order'),
    path('pay/<int:order_id>', views.pay_form, name='pay_form'),
    path('paid/<int:order_id>', views.paid_form, name='paid_form'),
    path('quiz/', views.quiz, name='quiz'),
    path('quiz_step/<int:event_id>', views.quiz_step, name='quiz_step'),
    path('result/<int:event_id>/<str:price_level>', views.result,
         name='result'),
    path('consultation/', views.consultation, name='consultation'),
    path('confidentcialnost/', views.confidentcialnost,
         name='confidentcialnost'),
]

shop/models.py
import os

from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from telegram import Bot
from textwrap import dedent
from dotenv import load_dotenv


class Event(models.Model):
    """События, к которым заказывают букеты."""
    name = models.CharField(max_length=30, verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Событие'
        verbose_name_plural = 'События'


class Bouquet(models.Model):
    """Букеты"""
    name = models.CharField(
        max_length=30,
        verbose_name='Название'
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name='Цена'
    )
    composition = models.TextField(
        verbose_name='Состав'
    )
    description = models.TextField(
        verbose_name='Описание',
        blank=True,
        null=True,
    )
    size = models.TextField(
        verbose_name='Размер'
    )
    events = models.ManyToManyField(
        Event,
        related_name='bouquets',
        verbose_name='Подходящие события'
    )
    photo = models.ImageField(
        verbose_name='Фото',
        null=True,
        blank=True,
    )

    def __str__(self):
        return f'{self.name} - {str(self.price)}р.'

    class Meta:
        verbose_name = 'Букет'
        verbose_name_plural = 'Букеты'


class Order(models.Model):
    """ Заказы """
    class Status(models.TextChoices):
        CREATED = 'NEW', 'Создан'
        PAID = 'PAID', 'Оплачен'
        DONE = 'DONE', 'Доставлен'

    client_name = models.CharField(
        max_length=50,
        verbose_name='Имя клиента'
    )
    phone = PhoneNumberField(
        verbose_name='Телефон',
    )
    address = models.CharField(
        max_length=150,
        verbose_name='Адрес доставки',
        db_index=True,
    )
    datetime_created = models.DateTimeField(
        verbose_name='Дата создания заказа',
        auto_now_add=True,
    )
    deliver = models.DateTimeField(
        verbose_name='Дата и время доставки',
        blank=True,
        null=True,
    )
    bouquet = models.ManyToManyField(
        Bouquet,
        related_name='orders',
    )
    status = models.CharField(
        max_length=4,
        choices=Status.choices,
        default=Status.CREATED
    )
    paid = models.BooleanField(
        default=False,
        verbose_name='Оплачено'
    )

    def __str__(self):
        return f'Заказ {self.pk} - {self.bouquet}'

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
        ordering = ['-datetime_created']
        indexes = [
            models.Index(fields=['-datetime_created', 'address']),
        ]

    def save(self, *args, **kwargs):
        super(Order, self).save(*args, **kwargs)
        if self.paid:
            load_dotenv()
            tg_bot_key = os.getenv('TG_BOT_KEY')
            user_id = os.getenv('CHAT_ID')
            bot = Bot(token=tg_bot_key)
            bouquets_text = ''
            for bouquet in self.bouquet.all():
                bouquets_text = bouquets_text + ' ' + bouquet.name
                print(bouquet.name)
            print(self.bouquet.all())
            message = f'''\
                        Новый заказ

                        Букет: {bouquets_text}
                        Клиент: {self.client_name}
                        Адрес: {self.address}
                        Время доставки: {str(self.deliver)}
                        
                        Телефон: {self.phone} '''
            bot.send_message(text=dedent(message), chat_id=user_id)


class Consultation(models.Model):
    """ Заявки на консультацию """
    client_name = models.CharField(
        max_length=50,
        verbose_name='Имя клиента'
    )
    phone = PhoneNumberField(
        verbose_name='Телефон'
    )
    datetime_created = models.DateTimeField(
        verbose_name='Дата запроса на косультацию',
        auto_now_add=True,
    )

    def __str__(self):
        return f'Консультация {self.pk} - {self.client_name}'

    class Meta:
        verbose_name = 'Консультация'
        verbose_name_plural = 'Консультации'

shop/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import RegionalPhoneNumberWidget


class ConsultationFortm(forms.Form):
    name = forms.CharField(
        max_length=25,
        widget=forms.widgets.TextInput(attrs={'class': 'order__form_input',
                                              'placeholder': 'Введите Имя'})
    )
    phone = PhoneNumberField(
        region='RU',
        widget=RegionalPhoneNumberWidget(
            region='RU',
            attrs={'class': 'order__form_input',
                   'placeholder': '+7 (999) 000 00 00'}
        ),
    )
    checkbox = forms.BooleanField(
        required=True,
        widget=forms.CheckboxInput(),
        label='Я согласен(а) с политикой конфиденциальности',
        initial=True
    )


class OrderForm(forms.Form):
    name = forms.CharField(
        max_length=25,
        widget=forms.widgets.TextInput(attrs={'class': 'order__form_input',
                                              'placeholder': 'Введите Имя'})
    )
    phone = PhoneNumberField(
        region='RU',
        widget=RegionalPhoneNumberWidget(
            region='RU',
            attrs={'class': 'order__form_input',
                   'placeholder': '+7 (999) 000 00 00'
                   }
        ),
    )
    address = forms.CharField(
        max_length=65,
        widget=forms.widgets.TextInput(attrs={'class': 'order__form_input',
                                              'placeholder': 'Адрес доставки'})
    )
    delivery_time = forms.ChoiceField(
        choices=(
            ('1', 'Как можно скорее'),
            ('10', 'с 10:00 до 12:00'),
            ('12', 'с 12:00 до 14:00'),
            ('14', 'с 14:00 до 16:00'),
            ('16', 'с 16-00 до 18-00'),
            ('18', 'с 18-00 до 20-00'),
        ),
        widget=forms.widgets.RadioSelect(),
    )

shop/views.py
import datetime
import os
import uuid

from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.db.models import Count
from django.core.paginator import Paginator
from django.urls import reverse
from django.utils import timezone

from .models import Bouquet, Event, Consultation, Order
from .forms import ConsultationFortm, OrderForm

from dotenv import load_dotenv
from yookassa import Configuration, Payment


def main_page(request):
    popular_bouquets = Bouquet.objects.all()\
        .annotate(count=Count('orders')).order_by('-count')[:3]
    form = ConsultationFortm()
    return render(request, 'index.html', {
        'recomendations': popular_bouquets,
        'form': form,
    })


def catalog(request):
    catalog_bouquets = Bouquet.objects.all()
    paginator = Paginator(catalog_bouquets, 6)
    number_pages = int(request.GET.get('page', 1))
    bouquets = []
    form = ConsultationFortm()
    for page in range(1, number_pages + 1):
        print('We are here')
        bouquets = bouquets + list(paginator.page(page))
    chunks = [bouquets[i:i + 3] for i in range(0, len(bouquets), 3)]
    next_page = number_pages + 1
    button = True
    if paginator.num_pages <= number_pages:
        button = False
    return render(request, 'catalog.html', {
        'catalog': chunks,
        'next_page': next_page,
        'button': button,
        'form': form,
    })


def show_card(request, id):
    bouquet = get_object_or_404(Bouquet, id=id)
    form = ConsultationFortm()
    return render(request, 'card.html', {
        'bouquet': bouquet,
        'form': form,
    })


def order(request):
    bouquet_id = request.GET.get('bouquet', 1)
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order_data = form.cleaned_data
            print(order_data)
            now = timezone.now()
            if order_data['delivery_time'] == '1':
                if now.time() < datetime.time(hour=20):
                    time = datetime.time(hour=10) if now.time() <= \
                        datetime.time(hour=8) else now + \
                        datetime.timedelta(hours=2)
                    delivery_time = datetime.datetime.combine(now.date(), time)
                else:
                    tomorrow = (now + datetime.timedelta(days=1)).date()
                    time = datetime.time(hour=10)
                    delivery_time = datetime.datetime.combine(tomorrow, time)
            else:
                time = datetime.time(hour=int(order_data['delivery_time']))
                if now.time() > time:
                    tomorrow = (now + datetime.timedelta(days=1)).date()
                    delivery_time = datetime.datetime.combine(tomorrow, time)
                else:
                    delivery_time = datetime.datetime.combine(now.date(), time)

            name = order_data['name']
            phone = order_data['phone']
            address = order_data['address']
            bouquet = Bouquet.objects.get(id=bouquet_id)
            new_order = Order(
                client_name=name,
                phone=phone,
                address=address,
                deliver=delivery_time,
                status=Order.Status.CREATED,
            )
            new_order.save()
            new_order.bouquet.set([bouquet])

            return HttpResponseRedirect(reverse('shop:pay_form',
                                                args=(new_order.id,)))

    form = OrderForm()
    return render(request, 'order.html', {
        'id': bouquet_id,
        'form': form,
    })


def pay_form(request, order_id):
    load_dotenv()
    account_id = os.getenv('ACCOUNT_ID')
    secret_key = os.getenv('SECRET_KEY')
    Configuration.configure(account_id, secret_key)

    idempotence_key = str(uuid.uuid4())
    return_url = request.build_absolute_uri(reverse('shop:paid_form',
                                                    args=(order_id,)))

    bouquet = Order.bouquet.all().first()
    payment = Payment.create({
        "amount": {
            "value": bouquet.price,
            "currency": "RUB"
        },
        "payment_method_data": {
            "type": "bank_card"
        },
        "confirmation": {
            "type": "redirect",
            "return_url": return_url
        },
        "description": bouquet.name
    }, idempotence_key)

    confirmation_url = payment.confirmation.confirmation_url

    return HttpResponseRedirect(confirmation_url)


def paid_form(request, order_id):
    order = Order.objects.get(id=order_id)
    order.paid = True
    order.save()
    return main_page(request)
    #return render(request, 'order-step.html', {})


def quiz(request):
    events = Event.objects.all()
    return render(request, 'quiz.html', {'events': events})


def quiz_step(request, event_id):
    return render(request, 'quiz-step.html', {'event_id': event_id})


def result(request, event_id, price_level):
    form = ConsultationFortm()
    match price_level:
        case 'low':
            best_bouquet = Event.objects.get(pk=event_id).bouquets.all()\
                .filter(price__lt=2000).first()
        case 'mid':
            best_bouquet = Event.objects.get(pk=event_id).bouquets.all()\
                .filter(price__gt=2000, price__lt=5000).first()
        case 'top':
            best_bouquet = Event.objects.get(pk=event_id).bouquets.all()\
                .filter(price__gt=5000).first()
        case _:
            best_bouquet = Event.objects.get(pk=event_id).bouquets.all()\
                .first()
    return render(request, 'result.html', {'bouquet': best_bouquet,
                                           'form': form})


def consultation(request):
    mark = False
    if request.method == 'POST':
        form = ConsultationFortm(request.POST)
        if form.is_valid():
            client_data = form.cleaned_data

            appointment = Consultation(
                client_name=client_data['name'],
                phone=client_data['phone']
            )
            appointment.save()
            mark = True
    else:
        form = ConsultationFortm()
    return render(request, 'consultation.html', {
        'form': form,
        'mark': mark,
    })


def confidentcialnost(request):
    return render(request, 'confidentcialnost.html', {})

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Flower Shop</title>
	<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&family=Unbounded:wght@700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="{% static "css/main.css" %}">
</head>
<body>
	<div class="mainBg">
		<header id="header">
			<div class="container">
				<div class="header ficb">
					<a href="/"><img src="{% static "img/logo.svg" %}" alt="logo" class="logo"></a>
					<nav>
						<ul class="menu ficc">
							<li class="menu__item"><a href="{% url "shop:catalog" %}" class="menu__item_link">Каталог</a></li>
							<li class="menu__item"><a href="{% url "shop:main_page" %}#recommended" class="menu__item_link">Рекомендации</a></li>
							<li class="menu__item"><a href="{% url "shop:main_page" %}#contacts" class="menu__item_link">Контакты</a></li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
        {% block banner %}
        {% endblock %}
    </div>

    {% block content %}
    {% endblock %}

    {% block contacts %}
    {% endblock %}

    {% block consultation %}
    {% endblock %}

	{% block quiz %}
	{% endblock %}

	{% block quiz_step %}
	{% endblock %}

	{% block result %}
	{% endblock %}

	<footer id="footer">
		<div class="container">
			<div class="footer">
				<a href="/"><img src="{% static "img/logo.svg" %}" alt="logo" class="logo footer__logo"></a>
				<nav>
					<ul class="menu footer__menu ficc">
						<li class="menu__item"><a href="{% url "shop:catalog" %}" class="menu__item_link">Каталог</a></li>
						<li class="menu__item"><a href="{% url "shop:main_page" %}#recommended" class="menu__item_link">Рекомендации</a></li>
						<li class="menu__item"><a href="{% url "shop:main_page" %}#contacts" class="menu__item_link">Контакты</a></li>
					</ul>
				</nav>
				<hr class="line"></hr>
				<a href="{% url "shop:confidentcialnost" %}" class="footer__poli">Политика конфиденциальности</a>
				<p class="footer_cop">©️2022. FlowerShop. Все права защищены</p>
			</div>
		</div>
	</footer>
</body>
</html>    

shop/templates/block-consultation.html
<section id="consultation">
    <div class="container">
        <div class="consultation">
            <div class="title consultation__title">Оставьте заявку на консультацию</div>
            <form action="{% url "shop:consultation" %}" class="consultation__form" method="post">
              {% for field in form %}
                {% if field.name == 'checkbox' %}
                  {{ field }}	<span class="chekbox__intro">{{ field.label_tag }}</span>
                {% else %}
                  {{ field }}
                  {{ field.error }}
                {% endif %}
              {% endfor %}
              {% csrf_token %}
_              <button type="submit" class="consultation__form_btn">Отправить</button>
            </form>
        </div>
    </div>
</section>

shop/templates/card.html
{% extends "base.html" %}
  {% block banner %}
  {% endblock %}

  {% block content %}
	<section id="card">
		<div class="container">
			<div class="card ficb">
				<div class="card__block card__block_first">
					<img src="{{ bouquet.photo.url }}" alt="img" class="card__img">
				</div>
				<div class="card__block card__block_sec">
					<div class="title">{{ bouquet.name }}</div>
					<div class="card__block_price">{{ bouquet.price }} руб</div>
					<div class="card__elems ">
						<span class="card__elems_intro">Состав</span>
						<div class="card__items">
							<span class="card_items_intro">
								{{ bouquet.composition|linebreaks }}
							</span>
						</div>
					</div>
					<div class="card__elems ">
						<span class="card__elems_intro">Размер</span>
						<div class="card__items">
							<span class="card_items_intro">
								{{ bouquet.size|linebreaks }}
							</span>
						</div>
					</div>
					<button class="btn largeBtn card__btn" onclick="window.location.href='{% url "shop:order" %}?bouquet={{ bouquet.id }}'">Заказать букет</button>
				</div>
			</div>
		</div>
	</section>
  {% endblock %}
  {% block consultation %}
    {% include "block-consultation.html" %}
  {% endblock %}

shop/templates/catalog.html
{% extends "base.html" %}
  {% block banner %}
  {% endblock %}

  {% block content %}
	<section id="catalog">
		<div class="container p100">
			<div class="catalog">
				<div class="title">Все букеты</div>
				<div class="catalog__block">
				  {% for row in catalog %}
					<div class="recommended__elems ficb">
					  {% for bouquet in row %}
						<div class="recommended__block_elems">
							<a class="recommended__block ficb" style="background: url('{{ bouquet.photo.url }}') no-repeat center bottom / cover; display: block;" href="{% url "shop:card" bouquet.id %}">
							  <div class="recommended__block ficb">
								<span class="recommended__block_intro">{{ bouquet.name }}</span>
								<span class="recommended__block_price">{{ bouquet.price }} руб</span>
							</div>
							</a>
						</div>
					  {% endfor %}
					</div>
				  {% endfor %}
				  {% if button %}
					<button class="btn largeBtn catalog__btn" onclick="window.location.href='?page={{ next_page }}';">Показать ещё</button>
				  {% endif %}
				</div>
			</div>
		</div>
	</section>
  {% endblock %}

  {% block contacts %}
  {% endblock %}

  {% block consultation %}
	{% include "block-consultation.html" %}
  {% endblock %}

shop/templates/consultation.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<section id="singUpConsultation">
		<div class="container">
			<div class="singUpConsultation">
			  {% if mark %}
				<div style="margin-top: 200px; font-size: 32px;">
				  Отлично, скоро с вами свяжемся. А пока можете присмотреть что-нибудь из готовой коллекции
				  <div style="padding-left: 20%; padding-top: 40px;">
				  	<button class="btn singUpConsultation__form_btn" onclick="window.location.href='{% url "shop:catalog" %}'">Посмотреть</button>
				  </div>
				</div>
			  {% else %}
				<form action="#" class="singUpConsultation__form" method="post">
					<div class="title">Запись на консультацию</div>
					{% for field in form %}
					  {% if field.name == 'checkbox' %}
					    <div class="chekbox fic">
							{{ field }}	<span class="chekbox__intro">{{ field.label_tag }}</span>
						</div>
					  {% else %}
					      {{ field }}
						  {{ field.errors}}
					  {% endif %}
					{% endfor %}
					{% csrf_token %}
					<button class="btn singUpConsultation__form_btn" type="submit">Отправить</button>	
				</form>
			  {% endif %}
				<div class="blockImgHiden"></div>
			</div>
		</div>
		<img src="{% static "img/singUpConsultationImg.jpg" %}" alt="singUpConsultationImg" class="singUpConsultation__img">
	</section>
{% endblock %}

shop/templates/index.html
{% extends "base.html" %}
{% load static %}
	{% block banner %}
		<section id="banner">
			<div class="container">
				<div class="banner">
					<div class="banner__block">
						<h1 class="banner__title">Мастерская цветов</h1>
						<p class="banner__text">Подберем для вас букет за два шага, который идеально подойдет под вашу ситуацию</p>
						<button class="btn banner__btn" onclick="location.href='{% url 'shop:quiz' %}'">Подобрать букет</button>
					</div>
					<img src="{% static "img/bannerImg.png" %}" alt="banner Img" class="banner__img">
				</div>
			</div>
		</section>
	{% endblock %}
	{% block content %}
	  <section id="recommended">
		<div class="container">
			<img src="{{ bouquet.photo.url }}">
			<div class="recommended p100">
				<div class="title">Рекомендуем</div>
				  <div class="recommended__elems ficb">
				  {% for bouquet in recomendations %}
				  	<a class="recommended__block" style="background: url('{{ bouquet.photo.url }}'); display: block;" href="{% url "shop:card" bouquet.id %}">
				      <div class="recommended__block ficb">
						<span class="recommended__block_intro">{{ bouquet.name }}</span>
						<span class="recommended__block_price">{{ bouquet.price }} руб</span>
					  </div>
					</a>
				  {% endfor %}
				</div>
				<button class="btn recommended__btn" onclick="window.location.href='{% url "shop:catalog" %}';">Показать всю коллекцию</button>
			</div>
		</div>
	  </section>
	{% endblock %}
	{% block contacts %}
	  {% include "contacts.html" %}
	{% endblock %}
	{% block consultation %}
	  {% include "block-consultation.html" %}
	{% endblock %}

shop/templates/order.html
{% extends "base.html" %}
{% load static %}
{% block banner %}
{% endblock %}

{% block content %}
	<section id="order">
		<div class="container">
			<div class="order">
				<div class="order__block">
					<div class="order_items">
						<div class="title">Оформление доставки</div>
						<form action="#" class="order__form" method="post">
						  {% for field in form %}
							{% if field.name == 'delivery_time' %}
							  <div class="order__form_btns fic">
								  {% for choice in form.delivery_time %}
								  	<div class="order__form_radioBlock">
									  <span class="radioLable"> {{ choice }}</span>
									</div>
								  {% endfor %}
							  </div>
							{% else %}
							  {{ field }}
							  {{ field.error }}
							{% endif %}
						  {% endfor %}
						  {% csrf_token %}
							<div class="order__form_line"></div>
							<div class="order__form_btns ficb">
								<button type="submit" class="btn order__form_pay">Оплатить</button>
								<button class="btn order__form_btn" onclick="window.location.href='{% url "shop:card" id %}'">Назад</button>
							</div>
						</form>
					</div>
					
				</div>
			</div>
		</div>
		<img src="{% static "img/orderImg.jpg" %}" alt="orderImg" class="order__img">
	</section>
{% endblock %}

shop/templates/quiz-step.html
{% extends "base.html" %}
{% load static %}
	{% block content %}
	<section id="quiz">
		<div class="container">
			<div class="quiz">
				<div class="quiz__back ">
					<a href="#" class="quiz__back_link fic"><img src="{% static "img/arrow-left.svg" %}" alt="arrow-left" class="arrowLeft">
					<span class="quiz__back_intro" onclick="location.href='{% url "shop:quiz" %}'">Назад</span></a>
				</div>
				<div class="quiz__block">
					<h1 class="quiz__title">На какой бюджет рассчитываете?</h1>
					<div class="quiz__elems fic">
						<button class="quiz__elem" onclick="location.href='{% url 'shop:result' event_id=event_id price_level='low' %}'">До 1 000 руб</button>
						<button class="quiz__elem" onclick="location.href='{% url 'shop:result' event_id=event_id price_level='mid' %}'">1 000 - 5 000 руб</button>
						<button class="quiz__elem" onclick="location.href='{% url 'shop:result' event_id=event_id price_level='top' %}'">от 5 000 руб</button>
						<button class="quiz__elem" onclick="location.href='{% url 'shop:result' event_id=event_id price_level='any' %}'">Не имеет значения</button>
					</div>
					<div class="quiz__progress">
						<div class="quiz__progress_step">
							<span class="quiz__progress_num">1</span>
							<span class="quiz__progress_in"> шаг из </span>
							<span class="quiz__progress_num">2</span>
						</div>
						<div class="quiz__progress_line">
							<div class="quiz__progress_lineActive"></div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
	</section>
	{% endblock %}

shop/templates/quiz.html
{% extends "base.html" %}
{% load static %}
{% block banner %}
{% endblock %}

{% block content %}
	<section id="quiz">
		<div class="container">
			<div class="quiz">
				<div class="quiz__back ">
					<a href="#" class="quiz__back_link fic"><img src="{% static "img/arrow-left.svg" %}" alt="arrow-left" class="arrowLeft">
					<span class="quiz__back_intro" onclick="location.href='{% url "shop:main_page" %}'">Назад</span></a>
					</div>
					<div class="quiz__block">
						<h1 class="quiz__title">К какому событию нужен букет?</h1>
						<div class="quiz__elems fic">
							{% for event in events %}
								<button class="quiz__elem" onclick="location.href='{% url 'shop:quiz_step' event_id=event.id %}'">{{event.name}}</button>
							{% endfor %}
						</div>
						<div class="quiz__progress">
							<div class="quiz__progress_step">
								<span class="quiz__progress_num">1</span>
								<span class="quiz__progress_in"> шаг из </span>
								<span class="quiz__progress_num">2</span>
							</div>
							<div class="quiz__progress_line">
								<div class="quiz__progress_lineActive"></div>
							</div>
						</div>
					</div>

				</div>
			</div>
		</section>
	{% endblock %}

shop/templates/result.html
{% extends "base.html" %}
{% load static %}
  {% block content %}
	<section id="result">
		<div class="container">
			<div class="result p100">
				<div class="title">Мы подобрали специально для Вас</div>
				<div class="result__block ficb">
					<div class="result__elems">
						<div class="card__elems ">
							<span class="card__elems_intro">Описание:</span>
							<div class="card__items">
								<p class="card__items_text card__items_text__first">
									{{ bouquet.description|linebreaksbr }}
								</p>
							</div>
						</div>
						<div class="card__elems ">
							<span class="card__elems_intro">Состав:</span>
							<div class="card__items">
								<p class="card__items_text card__items_text__first">
									{{ bouquet.composition|linebreaks }}
								</p>
								
							</div>
						</div>
					</div>
					<img src="{{ bouquet.photo.url }}" alt="result Img" class="result__block_img">
					<div class="result__items">
						<div class="title result__items_title">{{ bouquet.name }}</div>
						<div class="result__items_price">{{ bouquet.price }} руб</div>
						<button class="btn result__items_btn" onclick="window.location.href='{% url "shop:order" %}?bouquet={{ bouquet.id }}'">Заказать букет</button>
						<hr class="result__items_line" />
						<div class="result__items_intro">Хотите что-то более специальное?</div>
						<div class="result__items_block">
							<button class="btn largeBtn result__items_block__btn" onclick="location.href='{% url "shop:catalog" %}'">Смотреть всю коллекцию</button>
							<button class="btn largeBtn result__items_block__btn" onclick="location.href='{% url "shop:consultation" %}'">Заказать консультацию</button>
						</div>
					</div>
				</div>	
			</div>
		</div>
	</section>
  {% endblock %}
  {% block contacts %}
    {% include "contacts.html" %}
  {% endblock %}
{% block consultation %}
  {% include "block-consultation.html" %}
{% endblock %}